### ISSUE TITLE
need repositories for some packages

### ISSUE THREAD

**Issue by newswangerd** [newswangerd/AleksandrDocker#3]
https://github.com/newswangerd/AleksandrDocker/blob/a0de5c8cda9cfd52d16632268730c06fbd91f114/Dockerfile#L16

php70w isn't in the default centos repos, so you need to add 3rd party repos before you can install it

**Comment by AlekKras** [comment]
RUN wget -q http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    wget -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm && \
    yum-config-manager --enable remi-php70 && \
    yum -y install php
